import { Router } from 'express';
import { authRoutes } from '../modules/auth/auth.routes.js';
import { userRoutes } from '../modules/users/user.routes.js';
import { roleRoutes } from '../modules/roles/role.routes.js';
import { companyRoutes } from '../modules/company/company.routes.js';
import { dashboardRoutes } from '../modules/dashboard/dashboard.routes.js';
import { categoryRoutes } from '../modules/categories/category.routes.js';
import { productRoutes } from '../modules/products/product.routes.js';
import { movementRoutes } from '../modules/movements/movement.routes.js';
import { supplierRoutes } from '../modules/suppliers/supplier.routes.js';
import { purchaseRoutes } from '../modules/purchases/purchase.routes.js';
import { customerRoutes } from '../modules/customers/customer.routes.js';
import { saleRoutes } from '../modules/sales/sale.routes.js';
import { paymentMethodRoutes } from '../modules/payment-methods/payment-method.routes.js';
import { paymentRoutes } from '../modules/payments/payment.routes.js';
import { quotationRoutes } from '../modules/quotations/quotation.routes.js';
import { orderRoutes } from '../modules/orders/order.routes.js';
import { invoiceRoutes } from '../modules/invoices/invoice.routes.js';
import { accountRoutes } from '../modules/accounts/account.routes.js';
import { journalEntryRoutes } from '../modules/journal-entries/journal-entry.routes.js';
import { reportRoutes } from '../modules/reports/report.routes.js';
import { permissionRoutes } from '../modules/permissions/permission.routes.js';
import { auditRoutes } from '../modules/audit/audit.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/company', companyRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/movements', movementRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/customers', customerRoutes);
router.use('/sales', saleRoutes);
router.use('/payment-methods', paymentMethodRoutes);
router.use('/payments', paymentRoutes);
router.use('/quotations', quotationRoutes);
router.use('/orders', orderRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/accounts', accountRoutes);
router.use('/journal-entries', journalEntryRoutes);
router.use('/reports', reportRoutes);
router.use('/permissions', permissionRoutes);
router.use('/audit', auditRoutes);

export { router as routes };
